services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -port 8001
    ports: ["8001:8001"]
    volumes:
      - dynamo_data:/home/dynamodblocal
    healthcheck:
      test: ["CMD", "bash", "-lc", "exec 3<>/dev/tcp/127.0.0.1/8001 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 30

  scrs-app:
    build: .
    depends_on:
      dynamodb-local:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_REGION: us-east-1
      DYNAMODB_ENDPOINT: http://dynamodb-local:8001
    stdin_open: true
    tty: true

volumes:
  dynamo_data: